services:
  flask-app:
    build:
      context: ./nlp-tools-backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - app-network

  nuxt-app:
    build:
      context: ./nlp-tools-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
